name: Auto merge PRs at 23:00 KST

on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-24.04
    steps:
      - name: Auto-merge pull requests
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_FORKS: true
